log:
  level: info

server:
  address: tcp://0.0.0.0:9091

theme: dark

default_2fa_method: totp

totp:
  issuer: authelia
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "*"
      policy: one_factor

session:
  name: authelia_session
  same_site: lax
  expiration: 3600
  inactivity: 300
  storage: jwt
  cookies:
    - name: authelia_session
      domain: auth.longstorymedia.com
      authelia_url: "https://auth.longstorymedia.com"

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt
