apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - name: registry
      port: 5000
      targetPort: registry
      nodePort: 31500
  type: NodePort
  publishNotReadyAddresses: false
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31501
      protocol: TCP
  selector:
    app: registry-ui