apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lsm-gateway
  namespace: nginx-gateway
  labels:
    app: lsm-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: nextcloud
      port: 3000
      protocol: HTTP
    # - name: ollama
    #   port: 11434
    #   protocol: HTTP
    # - name: llmmllab  # Removed - conflicts with ollama LoadBalancer port 8000
    #   port: 8000
    #   protocol: HTTP
    - name: dex
      port: 9091
      protocol: HTTP
    - name: registry
      port: 5000
      protocol: HTTP
    - name: grafana
      port: 3001
      protocol: HTTP
    - name: prometheus
      port: 9090
      protocol: HTTP
    - name: alertmanager
      port: 9093
      protocol: HTTP
    - name: fnf
      protocol: HTTP
      port: 8082
    # - name: maistro
    #   protocol: HTTP
    #   port: 8083
    - name: usrmgr
      protocol: HTTP
      port: 3333
    - name: pgadmin
      port: 8084
      protocol: HTTP
    # - name: inference
    #   port: 50051
    #   protocol: HTTP
    - name: registry-ui
      protocol: HTTP
      port: 8085
    - name: searxng
      protocol: HTTP
      port: 8086
    - name: steam
      protocol: HTTP
      port: 4567
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: gateway-policy
  namespace: nginx-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: lsm-gateway
  body:
    maxSize: "0"
--- # Nextcloud
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nc-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: nextcloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nextcloud
          namespace: nextcloud
          port: 8080
# --- # Ollama
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: ollama-route
#   namespace: nginx-gateway
# spec:
#   parentRefs:
#     - name: lsm-gateway
#       sectionName: ollama
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       filters:
#         - type: ExtensionRef
#           extensionRef:
#             group: gateway.nginx.org
#             kind: SnippetsFilter
#             name: ollama-timeout-snippet
#       backendRefs:
#         - name: ollama
#           namespace: ollama
#           port: 11434
# ---
# apiVersion: gateway.nginx.org/v1alpha1
# kind: ClientSettingsPolicy
# metadata:
#   name: ollama-timeout-policy
#   namespace: nginx-gateway
# spec:
#   targetRef:
#     group: gateway.networking.k8s.io
#     kind: HTTPRoute
#     name: ollama-route
#   body:
#     timeout: "0s"
#   keepAlive:
#     time: 9999s
#     timeout:
#       server: 9099s
#       header: 9999s
# ---
# apiVersion: gateway.nginx.org/v1alpha1
# kind: SnippetsFilter
# metadata:
#   name: ollama-timeout-snippet
#   namespace: nginx-gateway
# spec:
#   snippets:
#     - context: http
#       value: |
#         proxy_read_timeout 1800;
#         proxy_connect_timeout 1800;
#         proxy_send_timeout 1800;
#         send_timeout 1800;

# Removed llmmllab-route - conflicts with ollama LoadBalancer port 8000
# --- # stable-diffusion
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: llmmllab-route
#   namespace: nginx-gateway
# spec:
#   parentRefs:
#     - name: lsm-gateway
#       sectionName: llmmllab
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       # filters:
#       #   - type: ExtensionRef
#       #     extensionRef:
#       #       group: gateway.nginx.org
#       #       kind: SnippetsFilter
#       #       name: sd-timeout-snippet
#       backendRefs:
#         - name: ollama
#           namespace: ollama
#           port: 8000
# ---
# apiVersion: gateway.nginx.org/v1alpha1
# kind: ClientSettingsPolicy
# metadata:
#   name: sd-timeout-policy
#   namespace: nginx-gateway
# spec:
#   targetRef:
#     group: gateway.networking.k8s.io
#     kind: HTTPRoute
#     name: sd-route
#   body:
#     timeout: "0s"
#   keepAlive:
#     time: 9999s
#     timeout:
#       server: 9099s
#       header: 9999s
# ---
# apiVersion: gateway.nginx.org/v1alpha1
# kind: SnippetsFilter
# metadata:
#   name: sd-timeout-snippet
#   namespace: nginx-gateway
# spec:
#   snippets:
#     - context: http
#       value: |
#         proxy_read_timeout 1800;
#         proxy_connect_timeout 1800;
#         proxy_send_timeout 1800;
#         send_timeout 1800;
--- # dex timeout policy
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: auth-timeout-policy
  namespace: nginx-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: dex-route
  body:
    timeout: "300s"
  keepAlive:
    time: 300s
    timeout:
      server: 300s
      header: 300s
--- # dex
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      namespace: nginx-gateway
      sectionName: dex
  hostnames:
    - "auth.longstorymedia.com"
    - "localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
          method: OPTIONS
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dex
          namespace: auth
          port: 5556
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: "*"
              - name: Access-Control-Allow-Credentials
                value: "true"
              - name: Access-Control-Allow-Methods
                value: "GET, POST, OPTIONS"
              - name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
--- # usrmgr timeout policy
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: usrmgr-timeout-policy
  namespace: nginx-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: usrmgr-route
  body:
    timeout: "300s"
  keepAlive:
    time: 300s
    timeout:
      server: 300s
      header: 300s
--- # usrmgr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: usrmgr-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: usrmgr
  hostnames:
    - "auth.longstorymedia.com"
    - "localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: usrmgr
          namespace: auth
          port: 3333
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: "*"
              - name: Access-Control-Allow-Credentials
                value: "true"
              - name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE, OPTIONS"
              - name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
--- # Grafana
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: grafana
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          namespace: monitoring
          port: 80

--- # Prometheus
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: prometheus
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-kube-prometheus-prometheus
          namespace: monitoring
          port: 9090
--- # Alertmanager
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanager-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: alertmanager
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-kube-prometheus-alertmanager
          namespace: monitoring
          port: 9093
--- # fnf
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: fnf-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: fnf
  # hostnames:
  #   - press.longstorymedia.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/" # match all paths for this host
      backendRefs:
        - name: fnf
          port: 80
          namespace: fnf
          weight: 1
--- # Registry
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: registry
  hostnames:
    - "registry.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: registry
          namespace: registry
          port: 5000
          kind: Service
--- # maistro
# apiVersion: gateway.nginx.org/v1alpha1
# kind: ClientSettingsPolicy
# metadata:
#   name: maistro-websocket-policy
#   namespace: nginx-gateway
# spec:
#   targetRef:
#     group: gateway.networking.k8s.io
#     kind: HTTPRoute
#     name: maistro-route
#   body:
#     timeout: "0s"
#   keepAlive:
#     time: 3600s
#     timeout:
#       server: 3600s
#       header: 3600s
# ---
# apiVersion: gateway.nginx.org/v1alpha1
# kind: SnippetsFilter
# metadata:
#   name: maistro-websocket-snippet
#   namespace: nginx-gateway
# spec:
#   snippets:
#     - context: http
#       value: |
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_read_timeout 300s;
#         proxy_send_timeout 300s;
#         proxy_buffering off;
# ---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: maistro-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: maistro
  # hostnames:
  #   - "ai.longstorymedia.com"
  #   - "localhost"
  rules:
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /ws
    #   filters:
    #     - type: ExtensionRef
    #       extensionRef:
    #         group: gateway.nginx.org
    #         kind: SnippetsFilter
    #         name: maistro-websocket-snippet
    #   backendRefs:
    #     - name: maistro
    #       namespace: maistro
    #       port: 80
    #       kind: Service
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: maistro
          namespace: maistro
          port: 80
          kind: Service
--- # pgAdmin
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: pgadmin
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pgadmin
          namespace: psql
          port: 8084
# --- # Inference
# apiVersion: gateway.networking.k8s.io/v1
# kind: GRPCRoute
# metadata:
#   name: inference-route
#   namespace: nginx-gateway
# spec:
#   parentRefs:
#     - name: lsm-gateway
#       sectionName: inference
#   rules:
#     - backendRefs:
#         - name: inference
#           namespace: ollama
#           port: 50051
--- # Registry UI
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-ui-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: registry-ui
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: registry-ui
          namespace: registry
          port: 80
--- # SearxNG
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: searxng-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: searxng
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: searxng
          namespace: searxng
          port: 8080
--- # Steam
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: steam-route
  namespace: nginx-gateway
  annotations:
    nginx.org/websocket-services: "selkies-desktop-official"
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: steam
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: selkies-desktop-official
          namespace: steam
          port: 58080
