apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lsm-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: nextcloud
      port: 3000
      protocol: HTTP
    - name: ollama-phi3-5
      port: 11434
      protocol: HTTP
    - name: dex
      port: 9091
      protocol: HTTP
    - name: registry
      port: 5000
      protocol: HTTP
--- # Nextcloud
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-nc
  namespace: nextcloud
spec:
  to:
    - group: ""
      kind: Service
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nc-route
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: nextcloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nextcloud
          namespace: nextcloud
          port: 8080
--- # Ollama
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-ollama
  namespace: ollama
spec:
  to:
    - group: ""
      kind: Service
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama-phi3-5-route
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: ollama-phi3-5
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /phi3-5
      backendRefs:
        - name: phi3-5
          namespace: ollama
          port: 11434
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
    - matches:
        - path:
            type: PathPrefix
            value: /llama3-8b
      backendRefs:
        - name: llama3-8b
          namespace: ollama
          port: 11434
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
--- # dex
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-dex
  namespace: auth
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex-route
  namespace: default
spec:
  parentRefs:
    - name: lsm-gateway
      namespace: default
      sectionName: dex
  hostnames:
    - "auth.longstorymedia.com"
    - "localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
          method: OPTIONS
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dex
          namespace: auth
          port: 5556
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: "*"
              - name: Access-Control-Allow-Credentials
                value: "true"
              - name: Access-Control-Allow-Methods
                value: "GET, POST, OPTIONS"
              - name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
--- # registry
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-registry
  namespace: registry
spec:
  to:
    - group: ""
      kind: Service
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-route
spec:
  parentRefs:
    - name: lsm-gateway
      sectionName: registry
  hostnames:
    - "registry.longstorymedia.com"
    - "localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: registry
          namespace: registry
          port: 5000
