apiVersion: v1
kind: Service
metadata:
  name: desktop-service
  namespace: steam
  labels:
    app: linux-desktop
spec:
  selector:
    app: linux-desktop
  ports:
    - name: novnc
      port: 6080
      targetPort: 80
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
  type: ClusterIP
