issuer: https://auth.longstorymedia.com
storage:
  type: memory
web:
  http: 0.0.0.0:5556
  templates: /etc/dex/custom-templates/templates
frontend:
  # dir: /etc/dex/custom-templates
  issuer: Long Story Media
  extra:
    custom_message: "Welcome to Long Story Media"
logger:
  level: "debug"
staticClients:
  - id: public-client
    public: true
    name: "Public Client"
    redirectURIs:
      - "https://ai.longstorymedia.com/callback"
      - "http://localhost:5173/callback"
  - id: private-client
    secret: app-secret
    name: "Private Client"
    redirectURIs:
      - "https://ai.longstorymedia.com/callback"
      - "http://localhost:5173/callback"
# Set up an test user
# staticPasswords:
#   - email: "longstoryscott@gmail.com"
#     # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
#     hash: "$2y$10$JgJIIygki8q6wPQqMYbFNOVNkYse9bC2RNAp.1ARNopVcvA8Zm5Oq"
#     username: "lsm"
#     userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

connectors:
  - type: ldap
    id: ldap
    name: OpenLDAP
    config:
      host: openldap.auth.svc.cluster.local:389
      insecureNoSSL: true
      bindDN: "cn=admin,dc=longstorymedia,dc=com"
      bindPW: "6u!tar00!QAZ"
      userSearch:
        baseDN: "dc=longstorymedia,dc=com"
        filter: "(objectClass=person)"
        username: "uid"
        idAttr: "uid"
        emailAttr: "mail"
        nameAttr: "cn"
      groupSearch:
        baseDN: "dc=longstorymedia,dc=com"
        filter: "(objectClass=groupOfNames)"
        userMatchers:
          - userAttr: "dn"
            groupAttr: "member"
        nameAttr: "cn"

# Enable local users
# enablePasswordDB: true
# Allow password grants with local users
oauth2:
  skipApprovalScreen: true
  passwordConnector: ldap
