issuer: https://auth.longstorymedia.com
storage:
  type: memory
web:
  http: 0.0.0.0:5556
frontend:
  # dir: /etc/dex/dex-templates
  issuer: Long Story Media
  logo: ../../etc/dex/dex-templates/static/logo.png
  extra:
    custom_message: "Welcome to Long Story Media"
logger:
  level: "debug"
staticClients:
  - id: public-client
    public: true
    name: "Public Client"
    redirectURIs:
      - "https://ai.longstorymedia.com/callback"
      - "http://localhost:5173/callback"
  - id: lsm-client
    public: true
    name: "Long Story Media"
    redirectURIs:
      - "https://ai.longstorymedia.com/callback"
      - "https://auth.longstorymedia.com/callback"
      - "http://localhost:5173/callback"

connectors:
  - type: ldap
    id: ldap
    name: OpenLDAP
    config:
      host: openldap.auth.svc.cluster.local:389
      insecureNoSSL: true
      bindDN: "cn=admin,dc=longstorymedia,dc=com"
      bindPW: ${LDAP_ADMIN_PASSWORD}
      baseDN: "dc=longstorymedia,dc=com"
      userSearch:
        baseDN: "dc=longstorymedia,dc=com"
        filter: "(objectClass=person)"
        username: "uid"
        idAttr: "uid"
        emailAttr: "mail"
        nameAttr: "cn"
        preferredUsernameAttr: uid
        attributes: ["uid", "cn"]
      groupSearch:
        baseDN: "dc=longstorymedia,dc=com"
        filter: "(objectClass=groupOfNames)"
        userMatchers:
          - userAttr: "dn"
            groupAttr: "member"
        nameAttr: "cn"
      # Updated claims mapping to include both uid and groups
      claims:
        uid: ["uid"]
        groups: ["cn"]

# Enable local users
# enablePasswordDB: true
# Allow password grants with local users
oauth2:
  skipApprovalScreen: true
  passwordConnector: ldap
