apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: auth
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
    staticClients:
      - id: public-client
        public: true
        name: 'Public Client'
        redirectURIs:
          - 'https://example.com/oidc/callback'
      - id: private-client
        secret: app-secret
        name: 'Private Client'
        redirectURIs:
          - 'https://example.com/oidc/callback'
    # Set up an test user
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
        hash: "$2y$10$l4TfsKXd5ngGu9BanfeDYe7IRFzLAfONDI.VYLf8rjrSxMEtHjifu"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

    # Enable local users
    enablePasswordDB: true
    # Allow password grants with local users
    oauth2:
      skipApprovalScreen: true
      passwordConnector: local
