apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      initContainers:
        - name: render-config
          image: alpine:latest
          command:
            [
              "sh",
              "-c",
              "apk add --no-cache gettext && envsubst < /config-in/config.yaml > /config-out/config.yaml",
            ]
          env:
            - name: DEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: client-secret
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-admin-secret
                  key: LDAP_ADMIN_PASSWORD
          volumeMounts:
            - name: config-in
              mountPath: /config-in
              readOnly: true
            - name: config-out
              mountPath: /config-out
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.43.1
          securityContext:
            runAsUser: 0 # 0 is the root user
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: config-out
              mountPath: /etc/dex
            - name: dex-web
              mountPath: /etc/dex/dex-templates
            - name: dex-static
              mountPath: /etc/dex/dex-templates/static
            - name: dex-themes
              mountPath: /etc/dex/dex-templates/themes
            - name: dex-templates
              mountPath: /etc/dex/dex-templates/templates
          ports:
            - containerPort: 5556
          args:
            - dex
            - serve
            - /etc/dex/config.yaml
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DEX_LOG_LEVEL
              value: "debug"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-admin-secret
                  key: LDAP_ADMIN_PASSWORD
      volumes:
        - name: config-in
          configMap:
            name: config
        - name: config-out
          emptyDir: {}
        - name: dex-templates
          configMap:
            name: dex-templates
        - name: dex-static
          configMap:
            name: dex-static
        - name: dex-themes
          configMap:
            name: dex-themes
        - name: dex-web
          configMap:
            name: dex-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      initContainers:
        - name: copy-ldif
          image: busybox
          command: ["sh", "-c", "cp /ldif-src/* /ldif-seed/"]
          volumeMounts:
            - name: openldap-seed-ldif
              mountPath: /ldif-src
            - name: openldap-seed-ldif-writable
              mountPath: /ldif-seed
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
          env:
            - name: LDAP_ORGANISATION
              value: "Long Story Media"
            - name: LDAP_DOMAIN
              value: "longstorymedia.com"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-admin-secret
                  key: LDAP_ADMIN_PASSWORD
            - name: LDAP_SEED_LDIF_PATH
              value: "/ldif-seed"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: openldap-seed-ldif-writable
              mountPath: /ldif-seed
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-pvc
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-config-pvc
        - name: openldap-seed-ldif
          configMap:
            name: openldap-seed-ldif
        - name: openldap-seed-ldif-writable
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usrmgr
  namespace: auth
  labels:
    app: usrmgr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: usrmgr
  template:
    metadata:
      labels:
        app: usrmgr
    spec:
      containers:
        - name: usrmgr
          image: 192.168.0.71:31500/usrmgr:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: USRMGR_LOG_LEVEL
              value: "debug"
            - name: USRMGR_LDAP_URL
              value: "ldap://openldap.auth.svc.cluster.local:389"
            - name: USRMGR_LDAP_BIND_DN
              value: "cn=admin,dc=longstorymedia,dc=com"
            - name: USRMGR_BASE_DN
              value: "dc=longstorymedia,dc=com"
            - name: USRMGR_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-admin-secret
                  key: LDAP_ADMIN_PASSWORD
            - name: USRMGR_JWKS_URI
              value: http://dex.auth.svc.cluster.local:5556/keys
            - name: USRMGR_OAUTH_CLIENT_ID
              value: lsm-client
            - name: USRMGR_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: client-secret
          ports:
            - containerPort: 3333
              name: usrmgr
      # Add image pull secret for private registry
      imagePullSecrets:
        - name: registry-credentials
