apiVersion: v1
kind: Secret
metadata:
  name: dex-users
  namespace: auth
type: Opaque
stringData:
  config.yaml: |
    connectors:
    - type: static
      id: local
      name: Static
      config:
        users:
        - email: admin@example.com
          hash: $2y$12$eImiTXuWVxfM37uY4JANjQ== # bcrypt hash for "password"
          username: admin
          userID: "123"
