apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth
spec:
  selector:
    app: dex
  ports:
    - name: http
      protocol: TCP
      port: 5556
      targetPort: 5556
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: auth
spec:
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: usrmgr
  namespace: auth
spec:
  selector:
    app: usrmgr
  ports:
    - name: usrmgr
      protocol: TCP
      port: 3333
      targetPort: 3333
