apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
spec:
  selector:
    app: registry-ui
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31580
  type: NodePort
