apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
  namespace: "psql"
  labels:
    app: psql
spec:
  replicas: 1
  serviceName: psql
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      name: psql
      labels:
        app: psql
    spec:
      serviceAccountName: postgres
      automountServiceAccountToken: false
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: psql
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - storage
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      hostNetwork: false
      hostIPC: false
      containers:
        - name: postgres
          image: timescale/timescaledb-ha:pg17
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: POSTGRESQL_VOLUME_DIR
              value: "/home/postgres/pgdata"
            - name: POSTGRES_USER
              value: "lsm"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: psqlpw
            - name: POSTGRES_MULTIPLE_DATABASES
              value: "ollama,nextcloud"
            - name: PGROOT
              value: /home/postgres
            - name: PGDATA
              value: /home/postgres/pgdata/data
            - name: PGHOST
              value: /var/run/postgresql
            - name: PGLOG
              value: /home/postgres/pg_log
            - name: PGSOCKET
              value: /home/postgres/pgdata
            - name: POSTGRES_DB
              value: ollama
            - name: POSTGRESQL_UNIX_SOCKET_DIRECTORIES
              value: /home/postgres/pgdata
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            - name: POSTGRESQL_ENABLE_TLS
              value: "no"
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "false"
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: "false"
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: "false"
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: "off"
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: "error"
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit,timescaledb"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "lsm" -d postgres -h 127.0.0.1 -p 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - exec pg_isready -U "lsm" -d postgres -h 127.0.0.1 -p 5432
          resources:
            limits:
              cpu: "3"
              ephemeral-storage: 10Gi
              memory: 6Gi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /home/postgres/pgdata
            - name: postgresql-run
              mountPath: /var/run/postgresql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: postgresql-run
          emptyDir: {}
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "300Gi"
