---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: "wordpress"
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.7.1
    helm.sh/chart: wordpress-24.0.7
type: Opaque
data:
  wordpress-password: "ajA1S1hjT1ZjWg=="
---
