# Source: wordpress/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress
  namespace: "wordpress"
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.7.1
spec:
  accessModes:
    - "ReadWriteOnce"
    - "ReadWriteMany"
  resources:
    requests:
      storage: "50Gi"
