# Source: wordpress/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-mariadb
  namespace: "wordpress"
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.4.4
    helm.sh/chart: mariadb-20.0.0
    app.kubernetes.io/part-of: mariadb
automountServiceAccountToken: false
---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mariadb
  namespace: "wordpress"
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.4.4
    app.kubernetes.io/part-of: mariadb
type: Opaque
data:
  mariadb-root-password: "M0Nrek5TRWxoNg=="
  mariadb-password: "RnhSOUk3OUhiNw=="
---
# Source: wordpress/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: "wordpress"
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.7.1
type: Opaque
data:
  wordpress-password: "ajA1S1hjT1ZjWg=="
