apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-stack:3100
      access: proxy
      isDefault: false
      jsonData:
        maxLines: 1000
        derivedFields:
          - datasourceUid: Prometheus
            matcherRegex: "service=\"(?<service>\\w+)\""
            name: "service"
            url: 'dashboard/db/kubernetes-service-overview?var-service=$${__value.raw}'
