---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-memcached
  namespace: wordpress
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.32
    helm.sh/chart: memcached-7.5.2
  spec:
    type: ClusterIP
    ports:
      - name: memcache
        port: 11211
        targetPort: memcache
        nodePort: null
    publishNotReadyAddresses: true
    selector:
      app.kubernetes.io/instance: wordpress
      app.kubernetes.io/name: memcached
---
