apiVersion: v1
kind: Service
metadata:
  name: selkies-desktop-official
  namespace: steam
  labels:
    app: selkies-desktop-official
spec:
  type: ClusterIP
  ports:
    - port: 58080
      targetPort: 58080
      protocol: TCP
      name: http
  selector:
    app: selkies-desktop-official
