apiVersion: v1
kind: Service
metadata:
  name: selkies-turn-embedded
  namespace: steam
  labels:
    app: selkies-desktop-official
spec:
  type: NodePort
  selector:
    app: selkies-desktop-official
  ports:
    - name: turn-udp
      port: 3478
      protocol: UDP
      targetPort: 3478
      nodePort: 30478
    - name: turn-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
      nodePort: 30479
    - name: turn-relay-1
      port: 65532
      protocol: UDP
      targetPort: 65532
      nodePort: 30532
    - name: turn-relay-2
      port: 65533
      protocol: UDP
      targetPort: 65533
      nodePort: 30533
    - name: turn-relay-3
      port: 65534
      protocol: UDP
      targetPort: 65534
      nodePort: 30534
    - name: turn-relay-4
      port: 65535
      protocol: UDP
      targetPort: 65535
      nodePort: 30535
