apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.0
          args:
            - start-dev
          env:
            # - name: KEYCLOAK_ADMIN
            #   value: admin
            # - name: KEYCLOAK_ADMIN_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: secrets
            #       key: global_admin
            # - name: PROXY_ADDRESS_FORWARDING
            #   value: "true"
            - name: KEYCLOAK_LOGLEVEL
              value: DEBUG
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME
              value: auth.longstorymedia.com
            # - name: KC_HEALTH_ENABLED
            # value: "true"
            # - name: KC_HOSTNAME
            # value: auth.longstorymedia.com
            - name: KC_HTTP_ENABLED
              value: "true"
            # - name: KC_PROXY
            #   value: edge
            # - name: KC_PROXY_HEADERS
            #   value: xforwarded
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
          ports:
            - name: http
              containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 9000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
