apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      serviceAccountName: searxng
      automountServiceAccountToken: false
      containers:
        - name: searxng
          image: searxng/searxng:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SEARXNG_INSTANCE_NAME
              value: "SearXNG K3s"
            - name: SEARXNG_BASE_URL
              value: "http://192.168.0.71:32348/"
            - name: SEARXNG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: searxng_secret_key
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /var/cache/searxng
            - name: config
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: searxng-data
        - name: config
          configMap:
            name: searxng-config
