apiVersion: v1
kind: Secret
metadata:
  name: searxng-settings
  namespace: searxng
type: Opaque
stringData:
  settings.yml: |
    server:
      secret_key: "${SEARXNG_SECRET_KEY}"
    general:
      debug: false
      instance_name: "SearXNG K3s"
      default_doi_resolver: 'oadoi.org'
      enable_metrics: true
