apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: "redis"
spec:
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      nodePort: 32346
  type: LoadBalancer
  clusterIP: 10.43.189.45
  publishNotReadyAddresses: true
