apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fnf-pvc
  namespace: fnf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # PVC for WordPress persistent data
  # Optional: specify storageClassName if needed
  # storageClassName: nfs-storage-class
