apiVersion: v1
kind: Service
metadata:
  name: fnf
  namespace: fnf
spec:
  selector:
    app: fnf
  ports:
    - name: fnf
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP # internal service for WordPress
